/* Graphics loaders and palette setup. The art itself is generated by
   tools/assets.py into gfx_data.h; every load keeps the LCD running. */
#ifndef ARCADE
#pragma bank 4
#endif
#include "dotwing.h"
#include "gfx_data.h"

static const uint8_t face_y[DW_SHAPES] = {11, 11, 15, 11, 12};

void dw_load_common(void) BANKED {
  VBK_REG = 0;
  set_bkg_data(0, DW_BG_COMMON, bg_common);
  set_sprite_data(0, sizeof(obj_flight) / 16, obj_flight);
  set_sprite_data(DW_S_BOSSCORE, sizeof(obj_boss_core) / 16, obj_boss_core);
}

void dw_load_fleet(uint8_t lab) BANKED {
  VBK_REG = 0;
  set_sprite_data(DW_S_FLEET, 32, obj_fleets + (uint16_t)lab * 512u);
}

void dw_load_menu_sprites(void) BANKED {
  VBK_REG = 1;
  set_sprite_data(0, sizeof(obj_menu) / 16, obj_menu);
  VBK_REG = 0;
}

/* A look is shape, colour, face and gear: the profile or the builder's
   unsaved edit, so previews never touch the profile itself. */
void dw_load_portrait(const uint8_t *look) BANKED {
  VBK_REG = 1;
  set_sprite_data(DW_M_PORTRAIT, 16, obj_bodies + (uint16_t)look[0] * 256u);
  set_sprite_data(DW_M_FACE, 4, obj_faces + (uint16_t)look[2] * 64u);
  set_sprite_data(DW_M_GEAR, 8, obj_gears + (uint16_t)look[3] * 128u);
  VBK_REG = 0;
}

uint8_t dw_gear_y(uint8_t gear) BANKED { return gear_y[gear]; }
uint8_t dw_face_y(uint8_t shape) BANKED { return face_y[shape]; }

static void copy_pal(uint8_t slot, const palette_color_t *src, uint8_t count) {
  uint16_t *dst = dw_pal + slot;
  count <<= 2;
  while (count--) *dst++ = *src++;
}

/* Object palettes for flight: livery plane, the sector's rival lab colours
   for bullets and craft, plus the HUD's two background palettes. */
void dw_pal_flight(uint8_t sector) BANKED {
  uint8_t lab = (uint8_t)(sector - 1u) & 3u;
  copy_pal(32, pal_obj_flight, 8);
  dw_pal[32 + 2] = pal_livery[dw_profile.color * 4u + 2u];
  copy_pal(32 + 4 * OP_BULLET, pal_labs + lab * 12u, 3);
  copy_pal(4 * PAL_HUD, pal_hud, 2);
}

void dw_pal_menu(const uint8_t *look) BANKED {
  uint8_t color = look[1];
  copy_pal(0, pal_menu_bg, 8);
  copy_pal(32, pal_menu_obj, 8);
  copy_pal(32, pal_livery + color * 4u, 1);
  dw_pal[32 + 12 + 2] = pal_livery[color * 4u + 2u];
}

/* Six livery colours for the builder's swatches, in two object palettes. */
void dw_pal_swatches(void) BANKED {
  uint8_t i;
  for (i = 0; i < 6; ++i) dw_pal[32 + (i < 3 ? 20 : 28) + (i % 3u) + 1u] = pal_livery[i * 4u + 2u];
}

void dw_title_row(uint8_t row) BANKED {
  const uint8_t *map = title_map + (uint16_t)row * 40u;
  uint8_t x;
  for (x = 0; x < 20; ++x) {
    dw_rowbuf[x] = *map++;
    dw_rowatt[x] = *map++;
  }
  VBK_REG = 1;
  set_bkg_tiles(0, row, 20, 1, dw_rowatt);
  VBK_REG = 0;
  set_bkg_tiles(0, row, 20, 1, dw_rowbuf);
}

/* The illustrated title: tiles in the halves of both VRAM banks that
   flight scenery uses, so loading it never disturbs the common set. */
void dw_title_art(void) BANKED {
  uint8_t y;
  VBK_REG = 0;
  set_bkg_data(128, DW_TITLE_TILES > 128 ? 128 : DW_TITLE_TILES, title_tiles);
#if DW_TITLE_TILES > 128
  VBK_REG = 1;
  set_bkg_data(128, DW_TITLE_TILES - 128, title_tiles + 2048u);
  VBK_REG = 0;
#endif
  for (y = 0; y < 18; ++y) dw_title_row(y);
  copy_pal(0, pal_title, 8);
}
